#ifndef PROTOCOL_COMMANDS_H
#define PROTOCOL_COMMANDS_H

#define CMD_PING "PING"
#define CMD_GET_INFO "GET_INFO"
#define CMD_GET_PLATFORM_IO "GET_PLATFORM_IO"
#define CMD_GEN_IDENTITY "GEN_IDENTITY"
#define CMD_GET_PUBLIC_ID "GET_PUBLIC_ID"
#define CMD_SIGN_BYTES "SIGN_BYTES"
#define CMD_SIGN_HASH "SIGN_HASH"
#define CMD_TEST_OUTPUT "TEST_OUTPUT"

#endif
